### ISSUE TITLE
Build error - 'unicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by vielfarbig** [johnyf/nx2tikz#4]
Hello,

if I try to build it with `python setup.py install`, it gives the error:

```
  File "build/bdist.linux-x86_64/egg/nx2tikz/nx2tikz.py", line 67
    '\documentclass{{standalone}}\n'
    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape
```

I tried with python3.8.10 and old python3.2 (7 years old, roughly the time you uploaded it), but both does not work

Regards

**Comment by johnyf** [comment]
Thank you for reporting this error. Branch `main` has now been updated to work with Python 3.13.
